/**
 * MIT License
 *
 * Copyright (c) 2025 QIU YIXIANG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef UTEST_H
#define UTEST_H

/* Flags for the utest library. */
#define UTEST_FLAG_NONE
#define UTEST_FLAG_SHOW_CASE
#define UTEST_FLAG_SHOW_SUITE
#define UTEST_FLAG_STYLE_FULL
#define UTEST_FLAG_STOP_ON_FAILURE
#define UTEST_FLAG_DEFAULT

/* These macros are used for specific usage only, often combined with
   UTEST_STRINGIFY and UTEST_CONCATENATE to get the function name for the
   function pointer. */
#define UTEST_CASENAME_PREFIX
#define UTEST_SUITENAME_PREFIX

/* Declare a test case and run it. */
#define UTEST_TEST_CASE(CASE_NAME)
#define UTEST_RUN_TEST_CASE(CASE_NAME)

/* Declare a test suite and run it. */
#define UTEST_TEST_SUITE(SUITE_NAME)
#define UTEST_RUN_TEST_SUITE(SUITE_NAME)

/* Initialize the utest library. */
#define UTEST_BEGIN()
#define UTEST_END()

/* These macros are used to control the flags of the utest library. */
#define UTEST_SET_FLAG(FLAG)
#define UTEST_CLEAR_FLAG(FLAG)
#define UTEST_FLAG_RESET()

/* Integer assertions */
#define EXPECT_EQUAL_INT(ACTUAL, EXPECTED)
#define EXPECT_EQUAL_INT8(ACTUAL, EXPECTED)
#define EXPECT_EQUAL_INT16(ACTUAL, EXPECTED)
#define EXPECT_EQUAL_INT32(ACTUAL, EXPECTED)
#define EXPECT_EQUAL_INT64(ACTUAL, EXPECTED)

#define EXPECT_NOT_EQUAL_INT(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_INT8(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_INT16(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_INT32(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_INT64(ACTUAL, EXPECTED)

#define EXPECT_GREATER_INT(ACTUAL, EXPECTED)
#define EXPECT_GREATER_INT8(ACTUAL, EXPECTED)
#define EXPECT_GREATER_INT16(ACTUAL, EXPECTED)
#define EXPECT_GREATER_INT32(ACTUAL, EXPECTED)
#define EXPECT_GREATER_INT64(ACTUAL, EXPECTED)

#define EXPECT_GREATER_EQUAL_INT(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_INT8(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_INT16(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_INT32(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_INT64(ACTUAL, EXPECTED)

#define EXPECT_LESS_INT(ACTUAL, EXPECTED)
#define EXPECT_LESS_INT8(ACTUAL, EXPECTED)
#define EXPECT_LESS_INT16(ACTUAL, EXPECTED)
#define EXPECT_LESS_INT32(ACTUAL, EXPECTED)
#define EXPECT_LESS_INT64(ACTUAL, EXPECTED)

#define EXPECT_LESS_EQUAL_INT(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_INT8(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_INT16(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_INT32(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_INT64(ACTUAL, EXPECTED)

/* Unsigned integer assertions */
#define EXPECT_EQUAL_UINT(ACTUAL, EXPECTED)
#define EXPECT_EQUAL_UINT8(ACTUAL, EXPECTED)
#define EXPECT_EQUAL_UINT16(ACTUAL, EXPECTED)
#define EXPECT_EQUAL_UINT32(ACTUAL, EXPECTED)
#define EXPECT_EQUAL_UINT64(ACTUAL, EXPECTED)

#define EXPECT_NOT_EQUAL_UINT(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_UINT8(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_UINT16(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_UINT32(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_UINT64(ACTUAL, EXPECTED)

#define EXPECT_GREATER_UINT(ACTUAL, EXPECTED)
#define EXPECT_GREATER_UINT8(ACTUAL, EXPECTED)
#define EXPECT_GREATER_UINT16(ACTUAL, EXPECTED)
#define EXPECT_GREATER_UINT32(ACTUAL, EXPECTED)
#define EXPECT_GREATER_UINT64(ACTUAL, EXPECTED)

#define EXPECT_GREATER_EQUAL_UINT(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_UINT8(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_UINT16(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_UINT32(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_UINT64(ACTUAL, EXPECTED)

#define EXPECT_LESS_UINT(ACTUAL, EXPECTED)
#define EXPECT_LESS_UINT8(ACTUAL, EXPECTED)
#define EXPECT_LESS_UINT16(ACTUAL, EXPECTED)
#define EXPECT_LESS_UINT32(ACTUAL, EXPECTED)
#define EXPECT_LESS_UINT64(ACTUAL, EXPECTED)

#define EXPECT_LESS_EQUAL_UINT(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_UINT8(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_UINT16(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_UINT32(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_UINT64(ACTUAL, EXPECTED)

/* float assertion */
#define EXPECT_EQUAL_FLOAT(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_FLOAT(ACTUAL, EXPECTED)
#define EXPECT_GREATER_FLOAT(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_FLOAT(ACTUAL, EXPECTED)
#define EXPECT_LESS_FLOAT(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_FLOAT(ACTUAL, EXPECTED)

/* double assertion */
#define EXPECT_EQUAL_DOUBLE(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_DOUBLE(ACTUAL, EXPECTED)
#define EXPECT_GREATER_DOUBLE(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_DOUBLE(ACTUAL, EXPECTED)
#define EXPECT_LESS_DOUBLE(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_DOUBLE(ACTUAL, EXPECTED)

/* string assertion */
#define EXPECT_EQUAL_STRING(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_STRING(ACTUAL, EXPECTED)
#define EXPECT_GREATER_STRING(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_STRING(ACTUAL, EXPECTED)
#define EXPECT_LESS_STRING(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_STRING(ACTUAL, EXPECTED)

/* pointer assertion */
#define EXPECT_NULL(POINTER)
#define EXPECT_NOT_NULL(POINTER)

/* boolean expression */
#define EXPECT_TRUE(EXPRESSION)
#define EXPECT_FALSE(EXPRESSION)

/* character assertion */
#define EXPECT_EQUAL_CHAR(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_CHAR(ACTUAL, EXPECTED)
#define EXPECT_GREATER_CHAR(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_CHAR(ACTUAL, EXPECTED)
#define EXPECT_LESS_CHAR(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_CHAR(ACTUAL, EXPECTED)

/* unsigned character assertion */
#define EXPECT_EQUAL_UCHAR(ACTUAL, EXPECTED)
#define EXPECT_NOT_EQUAL_UCHAR(ACTUAL, EXPECTED)
#define EXPECT_GREATER_UCHAR(ACTUAL, EXPECTED)
#define EXPECT_GREATER_EQUAL_UCHAR(ACTUAL, EXPECTED)
#define EXPECT_LESS_UCHAR(ACTUAL, EXPECTED)
#define EXPECT_LESS_EQUAL_UCHAR(ACTUAL, EXPECTED)

#include <utest/core.h>

#endif